# Generated by Django 4.0.4 on 2022-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_mashina_narxi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mashina',
            options={'verbose_name': 'Mashina', 'verbose_name_plural': 'Mashinalar'},
        ),
        migrations.AlterField(
            model_name='mashina',
            name='yili1',
            field=models.DateField(verbose_name='Chiqarilgan yili'),
        ),
    ]
